#this will help you to change/make new branch ............
git checkout 
git checkout -b "mynewbranch" #creata and switch branch
git branch # this for all avialible branches
git branch "My New Branch" #create branch 
git merg # ........  
